### ISSUE TITLE
Creating a Contributors file

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [aviyelverse/aviyel-first-pr#12]
Making a new file for Contributors to put their details. In `README.md` I will add some changes something like contributing guidelines with images so it would be better for a beginner

**Comment by ghost** [comment]
A separate file for `contributors.md `is being tracked via #15 and assigned to @Asmit2952 

@gurjeetsinghvirdee , you can please work on contributor guidelines if possible

**Comment by gurjeetsinghvirdee** [comment]
@JoshuaPoddoku yeah sure I will work on this
