### ISSUE TITLE
Update README with more content

### ISSUE THREAD

**Issue by Evavic44** [aviyelverse/aviyel-first-pr#31]
A few things need to be added to the readme to help people effectively contribute to this project.

- [x] Contribution Guideline link.
- [ ] Aviyel Website link and logo.
- [ ] Simplify contribution steps to make it easier for beginners to contribute.

**Comment by gurjeetsinghvirdee** [comment]
@Evavic44 buddy Contribution Guideline link & Contribution Steps already there please check

**Comment by Evavic44** [comment]
Oh, I see the contributing guideline now. How did I miss that? Steps need to be more simplified.

**Comment by gurjeetsinghvirdee** [comment]
> Oh, I see the contributing guideline now. How did I miss that? Steps need to be more simplified.

Ok I will fix this in new PR

**Comment by gurjeetsinghvirdee** [comment]
hey @JoshuaPoddoku assign me this will work on this

**Comment by ghost** [comment]
Start working I'm away from my laptop cannot assign from mobile @gurjeetsinghvirdee (try self assigning if that works)

**Comment by gurjeetsinghvirdee** [comment]
> Start working I'm away from my laptop cannot assign from mobile @gurjeetsinghvirdee (try self assigning if that works)

you can assign from mobile also just scrolling at the end you have the option to assign

**Comment by Evavic44** [comment]
> Start working I'm away from my laptop cannot assign from mobile @gurjeetsinghvirdee (try self assigning if that works)

Only people added as collaborators can self assign issues to themselves

**Comment by siddharth2798** [comment]
assigned to @gurjeetsinghvirdee . sorry for the delay

**Comment by Kaybangz** [comment]
This website link and logo, should it come before or after the contribution guideline link?

**Comment by Dhravya** [comment]
I think having it before would make sense
